[dark2829&TlahuicoleSystem] correccion de la rama
jtezva/softitlan-index pull request #3
Opened 2021-11-01 16:18 UTC by dark2829

2021-11-17 19:12 UTC, SXPJB requested changes
Eliminar ese archivo, si no va tener nada
resources/assets/js/script.js

2021-11-17 19:12 UTC, SXPJB commented on resources/assets/css/styles.css
> +    /* font-weight: normal; */
Eliminar comentarios

2021-11-17 19:12 UTC, SXPJB commented on resources/assets/css/styles.css
> +    /*display: block;*/
Eliminar comentario

2021-11-17 19:12 UTC, SXPJB commented on resources/assets/css/styles.css
> +    /* border-radius: 1em; */
Eliminar comentario

2021-11-17 19:12 UTC, SXPJB commented on resources/assets/css/styles.css
> +    /*el estilo se agrego en linea*/
Eliminar comentario

2021-11-17 19:12 UTC, SXPJB commented on resources/assets/css/styles.css
> +    /* background: rgba(32, 33, 36, 0.85); */
Eliminar comentario

2021-11-17 19:12 UTC, SXPJB commented on resources/assets/css/styles.css
> +    /* width: 31.8%; */
Eliminar comentario

2021-11-17 19:12 UTC, SXPJB commented on resources/assets/css/styles.css
> +    /* background-image: url(https://drive.google.com/uc?id=1KSi7chZK9w6alPRu26Om6e5T_D0e3QEE); */
Eliminar comentario

2021-11-17 19:12 UTC, SXPJB commented on resources/assets/css/styles.css
> +    /* width: 92%; */
Eliminar comentario

2021-11-17 19:12 UTC, SXPJB commented on resources/assets/css/styles.css
> +    /* clip-path: polygon(25% 0%, 100% 0%, 100% 100%, 0% 100%); */
Eliminar comentario

2021-11-17 19:12 UTC, SXPJB commented on resources/assets/css/styles.css
> +    /* clip-path: polygon(9% 0%, 95% 0%, 76% 100%, 0% 100%); */
Eliminar comentario

2021-11-17 19:12 UTC, SXPJB commented on resources/assets/css/styles.css
> +    /* clip-path: polygon(0% 0%, 91% 0%, 78% 100%, 0% 100%); */
Eliminar comentario

2021-11-17 19:12 UTC, SXPJB commented on resources/assets/css/styles.css
> +    /* clip-path: polygon(25% 0%, 100% 0%, 75% 100%, 0% 100%); */
Eliminar comentario

2021-11-17 19:12 UTC, SXPJB commented on resources/assets/css/particulas.css
> +	/* background:#111; */
Eliminar comentario

2021-11-17 19:12 UTC, SXPJB commented on resources/assets/css/styles.css
> +        /* margin: -0% 0% 0% 0%; */
Eliminar comentario

2021-11-17 19:12 UTC, SXPJB commented on resources/assets/css/styles.css
> +        /* position: absolute; */
Eliminar comentario

2021-11-17 19:12 UTC, SXPJB commented on resources/assets/css/styles.css
> +        /*10 Modificar a -7 si es oneline*/
Eliminar comentario

2021-11-17 19:12 UTC, SXPJB commented on resources/assets/css/styles.css
> +        /*30 Modificar a -10 si es una linea*/
Eliminar comentario

2021-11-17 19:12 UTC, SXPJB commented on resources/assets/css/styles.css
> +        /*100 Modificar a 50 si es de una linea*/
Eliminar comentario

2021-11-17 19:12 UTC, SXPJB commented on resources/assets/css/styles.css
> +        /* background-image: url(https://drive.google.com/uc?id=1KSi7chZK9w6alPRu26Om6e5T_D0e3QEE); */
Eliminar comentario

2021-11-17 19:12 UTC, SXPJB commented on resources/assets/css/styles.css
> +        /* font-size: 2.5vw; */
Eliminar comentario

2021-11-17 19:12 UTC, SXPJB commented on resources/assets/css/styles.css
> +        /* width: 31.8%; */
Eliminar comentario

2021-11-17 19:12 UTC, SXPJB commented on resources/assets/css/styles.css
> +        /* background: rgba(32, 33, 36, 0.85); */
Eliminar comentario

2021-11-17 19:12 UTC, SXPJB commented on resources/assets/css/styles.css
> +        /*el estilo se agrego en linea*/
Eliminar comentario

2021-11-17 19:12 UTC, SXPJB commented on resources/assets/css/styles.css
> +        /* border-radius: 1em; */
Eliminar comentario

2021-11-17 19:12 UTC, SXPJB commented on resources/assets/css/styles.css
> +        /*display: block;*/
Eliminar comentario

2021-11-17 19:12 UTC, SXPJB commented on resources/assets/css/styles.css
> +        border: 2px solid #3F4042; */
Eliminar comentario

2021-11-17 19:12 UTC, SXPJB commented on resources/assets/php/contacto.php
> +}
Validar como llamar al al servicio.

2021-11-22 16:41 UTC, SXPJB requested changes
Validar esos cambior porfa

2021-11-22 16:41 UTC, SXPJB commented on resources/assets/css/styles.css
> +        /* background-image: url(https://drive.google.com/uc?id=1KSi7chZK9w6alPRu26Om6e5T_D0e3QEE); alternative*/
Eliminar comentario, solo colocar comentarios informativos no de codigo

2021-11-22 16:41 UTC, SXPJB commented on resources/assets/php/contacto.php
> +		echo '<script language="javascript">alert("Datos enviados");window.location.href="http://localhost:3000/index.html"</script>';
aqui hay que mandejar bien la ruta, cuando este en el servidor no va funcionar

2021-11-22 16:41 UTC, SXPJB commented on resources/assets/php/contacto.php
> +*/
Si todo esto ya no sirve, eliminar porfavor

2021-11-23 17:50 UTC, SXPJB approved these changes
Todo ok

2021-11-23 20:36 UTC, Harckh approved these changes
Comentarios generales
· Correcciones de ortografía que se tomarán en cuenta cuando se coloque la demás información
· Disminuir la velocidad de las partículas, se puede modificar posteriormente, también escuchando los comentarios de cuando se realicen pruebas
· El formulario de contacto funciona correctamente

2021-11-24 16:44 UTC, merged